### PR TITLE
Upgrade skynet-js and fix broken tests

### LINKED ISSUE #150: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'
Hello m-cat

I have just cleded "SkynetLabs/nodejs-skynet".
Next I changed the version to "4.1.0" in "package.json", and "yarn test".
All tests run clean. Great.

After that, in "package.json" I changed the version to "4.2.0-beta" because I have the "client.getFileContentBinary" and "client.getFileContentBinaryHns" still wanted to integrate in "SkynetLabs/nodejs-skynet".

I tested "scripts/skydb.js" and "scripts/skydb_v2.js", and everything ok.
Then I executed "Yarn Test".
And there are many errors.

Everywhere the same error from version "4.2.0-beta" upwards:
`Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'`

What's going on there?
I haven't changed anything on the code, just the "package.json"!

Hopefully you can help me find out the problem.

Here are the complete errors:
```
  ● SkyDB V1 › db.setDataLink › should be a dataLink set

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      29 |   describe("db.setDataLink", () => {
      30 |     it("should be a dataLink set", async () => {
    > 31 |       await client.db.setDataLink(privateKey, dataKey, dataLink);
         |       ^
      32 |     });
      33 |   });
      34 |

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at SkynetClient.setDataLink (node_modules/skynet-js/dist/cjs/skydb.js:140:5)
      at Object.<anonymous> (src/skydb.test.js:31:7)

  ● SkyDB V1 › db.setEntryData › should set entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      35 |   describe("db.setEntryData", () => {
      36 |     it("should set entryData", async () => {
    > 37 |       const receivedData = await client.db.setEntryData(privateKey, dataKey, rawEntryData);
         |                            ^
      38 |
      39 |       await expect(receivedData["data"]).toEqual(rawEntryData);
      40 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at Object.<anonymous> (src/skydb.test.js:37:28)

  ● SkyDB V1 › db.getEntryData › should get entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      43 |   describe("db.getEntryData", () => {
      44 |     it("should get entryData", async () => {
    > 45 |       const receivedData = await client.db.getEntryData(publicKey, dataKey);
         |                            ^
      46 |
      47 |       await expect(receivedData["data"]).toEqual(rawEntryData);
      48 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getEntryData (node_modules/skynet-js/dist/cjs/skydb.js:162:19)
      at Object.<anonymous> (src/skydb.test.js:45:28)

  ● SkyDB V1 › db.getRawBytes › should get rawBytes

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      51 |   describe("db.getRawBytes", () => {
      52 |     it("should get rawBytes", async () => {
    > 53 |       const receivedData = await client.db.getRawBytes(publicKey, dataKey);
         |                            ^
      54 |
      55 |       await expect(formatSkylink(receivedData["dataLink"])).toEqual(dataLink);
      56 |       await expect("[" + receivedData["data"] + "]").toEqual(rawBytesData);

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getRawBytes (node_modules/skynet-js/dist/cjs/skydb.js:246:19)
      at Object.<anonymous> (src/skydb.test.js:53:28)

  ● SkyDB V1 › db.setJSON › should set jsonData to skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      59 |
      60 |   // Fetch the current value to find out the revision.
    > 61 |   const signedEntry = await client.registry.getEntry(publicKey, dataKey, DEFAULT_GET_ENTRY_OPTIONS);
         |                       ^
      62 |
      63 |   const revision = getNextRevisionFromEntry(signedEntry.entry);
      64 |

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getOrCreateRegistryEntry (src/skydb.js:61:23)
      at SkynetClient.setJSONdbV1 (src/skydb.js:31:31)
      at Object.<anonymous> (src/skydb.test.js:62:28)

  ● SkyDB V1 › db.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      68 |   describe("db.getJSON", () => {
      69 |     it("should get jsonData from skydb", async () => {
    > 70 |       const receivedData = await client.db.getJSON(publicKey, dataKey);
         |                            ^
      71 |
      72 |       await expect(receivedData.data).toEqual(data);
      73 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getJSON (node_modules/skynet-js/dist/cjs/skydb.js:44:19)
      at Object.<anonymous> (src/skydb.test.js:70:28)

  ● SkyDB V1 › db.deleteJSON › should delete jsonData on skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      76 |   describe("db.deleteJSON", () => {
      77 |     it("should delete jsonData on skydb", async () => {
    > 78 |       await client.db.deleteJSON(privateKey, dataKey);
         |       ^
      79 |       const receivedData = await client.db.getJSON(publicKey, dataKey);
      80 |
      81 |       await expect(receivedData.data).toEqual(null);

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at SkynetClient.deleteJSON (node_modules/skynet-js/dist/cjs/skydb.js:119:5)
      at Object.<anonymous> (src/skydb.test.js:78:7)

 FAIL  src/skydb_v2.test.js
  ● SkyDB V2 › dbV2.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

  ● SkyDB V2 › dbV2.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

  ● SkyDB V2 › dbV2.getEntryData › should get entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:229:23

  ● SkyDB V2 › dbV2.getRawBytes › should get rawBytes

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:329:23

  ● SkyDB V2 › dbV2.deleteJSON › should delete jsonData on skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23
```

### PR DESCRIPTION
**Pull request by m-cat**
# PULL REQUEST

## Overview

Upgrade `skynet-js`. Doing so broke the tests so I fixed that.

### More Details

The only relevant thing that changed in v4.2.0-beta is that we updated the axios
dependency, and it would seem like it behaves differently now. Previously, we
were partially mocking axios, but that didn't have any effect on the tests. Now,
however, it seems like the mock does not let through any actual network
requests, even if it is a partial mock. To fix this, all of the requests would
have to be mocked.

But I think it would be more valuable to let these tests keep making actual
network requests. I will remove the partial mock as it was actually a mistake
and not doing anything.

Credit: Thanks @parajbs!

## Checklist

- [x] All git commits are signed. (REQUIRED)
- [x] All new methods or updated methods have clear docstrings.
- [x] Testing added or updated for new methods.
- [x] Verified if any changes impact the WebPortal Health Checks.
- [x] Appropriate documentation updated.
- [x] Changelog file created.

## Issues Closed

Closes #150

### CODE REVIEW

**Comment by parajbs** [comment]
hello m-cat,

i have three questions.
1. what is the difference between ""tus-js-client": "^2.3.0"" and "@skynetlabs/tus-js-client": "^2.4.1" ?
2. if you use "@skynetlabs/tus-js-client": "^2.4.1" in "yarn.lock", don't you need to change the "package.json" as well? or am I confusing something?
3. when will "skynet-js@4.2.4-beta" come as npm? Since the "downloadFileHns" iusses was only removed there.

i was waiting for an answer, and in the meantime working on the integration of "pinSkylink" and all the function "Download area" and others. I also dealt with "jest" and "axios" and tried to get these tests done with "axios".
However, it took me a while to understand the basics.

I can try again to get it working with "axios". Again it may take time to port it from "skydb.test.ts" but I think it should work then.

**Comment by m-cat** [comment]
@parajbs Thanks for the questions.

> what is the difference between ""tus-js-client": "^2.3.0"" and "@skynetlabs/tus-js-client": "^2.4.1" ?

We are not using any features here from our fork of `tus-js-client`, but we might as well depend on it - it would be one less dependency.

> when will "[skynet-js@4.2.4-beta](mailto:skynet-js@4.2.4-beta)" come as npm? Since the "downloadFileHns" iusses was only removed there.

I'll just release that in the next stable version, which I plan on publishing early next week.

> I can try again to get it working with "axios". Again it may take time to port it from "skydb.test.ts" but I think it should work then.

I don't think it's worth the effort. The tests currently make real network requests which is enough to prove that the SkyDB integration works. Having more test coverage would be nice, but this Node SDK is not our top priority, so the cost:benefit just isn't there.

**Comment by parajbs** [comment]
hello m-cat,

i'll finish the other functions including test today, but first have to wait for the "skynet-js@4.2.4-beta" version to be released, so I can see if I can do it.
if not, then the tests are initially without "axios".

however, I have changed the portal from "https://siasky.net/" to "https://fileportal.org/" because "https://siasky.net/" has often led to errors 500 has led.

with "https://fileportal.org/" it works better great without an error.

**Review by kwypchlo — COMMENTED** [review]
Looks like the test are failing. Also would it be a lot of effort to mock those requests again? I'd much rather have those as unit tests than integration tests if possible.

**Comment by parajbs** [comment]
hello kwypchlo,

**The test failed is due to something else.
m-cat updated the "tus-js-client" to "@skynetlabs/tus-js-client", the error occurred in "upload.tset.js".**
Still needs to be changed.

I tried mocking the requests again tonight with no luck.
there are too many problems for me that I don't understand, because I know and understand too little "axios".

I tried porting the "skydb.test.ts" from "skynet-js" to "nodejs-skynet".
You can try it if you are familiar with "axios".
****

**Comment by parajbs** [comment]
hello **m-cat and kwypchlo,**

I went back to the problem with mocking, and was able to port the "skydb.test.ts" and "skydb_v2.test.ts" from "skynet-js" to "nodejs-skynet".

But I had to port many functions and variables in "nodejs-skynet" to "src/defaults.js".
I put things that I didn't know where to put them in "src/defaults.js" so that I can export them.
Thus the "src/defaults.js" has become full and not sorted and confusing.
**We should sort them later.**

Oh, but I can't upload the new test until "skynet-js@4.2.4-beta" comes out, because I want to upload the new test with a new RP from me with new ported functions.
It's less work for me then, and I also have to wait until this PR has been integrated into the master.

**So short and sweet. I was able to mock the test.**

**Comment by m-cat** [comment]
Nice @parajbs. I'll try to have a new `skynet-js` version out on Monday.

**Comment by parajbs** [comment]
hello m-cut,

But I have to say something about the test.

And they are the original test from "skynet-js", but corrected a little and ported some more.

But it's not the tests from "nodejs-skynet" that are in the repo at the moment.
Because it was easier

**Comment by parajbs** [comment]
hello **m-cat,**

I still have a problem with the download test and file test.
To run some tests, I needed a userID and an encrypted JsonFile on skynet.

**For this I used my main userId from mysky, and for the JsonFile I used "profile-dac.hns/exampleDomain/preferences.json".**
Since I still don't have an hns domain, I used my test TDL domain to see if it works.
It also works, but with my UserId and my tdl domain.

**This is not acceptable for me. I still have to figure out how to solve this.**

Do you have an idea?
It would be cool if you could create a real demo "userID" / "pathSeed" and jsonFile incl. path for testing.

So that I can then use them in "scripts/fils.js" as "defaultUserId" and "defaultPathSeed" if no parameter is specified in the command line.

I also have to change documentation in various files.

**Comment by parajbs** [comment]
hello **m-cat,**

Cool. Now I can switch my new repo to "skynet-js@4.3.0" and officially test everything.
If everything is ok, I'll create a new RP with many new functions from "skynet-js".

Since there is a lot of code, the code design may not be quite right, or the names of functions and variables may be poorly chosen.

Furthermore, I put all tests in the new RP, even if they are duplicates, then we can decide which test to delete.
There is also another problem which I haven't fixed yet, but more later when I've created the RP.

I also set my git to always sign everything, so this problem no longer exists.

**I looked at the last errors here. 
I cloned and tested the commit with git. Everything was ok.**

**This means that the errors came because something was probably wrong with the portal / skydb or registry on skynet at the time of the test on "github.com" or was even down.
All tests are OK for me. I tested it several times.**

**Comment by parajbs** [comment]
hello m-cat,

I just pushed a new PR.
here link: https://github.com/SkynetLabs/nodejs-skynet/pull/157

Since there is a lot of code, the code design may not be quite right, or the names of functions and variables may be poorly chosen.

Furthermore, I put all tests in the new RP, even if they are duplicates, then we can decide which test to delete.

There's also another problem that I haven't figured out yet. Take a look at "scripts/mysky.js", there are still problems with "loadMySky". But I left it in the code for now so you can test it and maybe have an idea how I could solve the problem. maybe it doesn't work.

The only problem at the moment

**Comment by m-cat** [comment]
@parajbs I hid your last comment so that the discussion here can stay on-topic. You don't need to call my attention to discussions and PRs happening elsewhere - I'm staying on top of it all, it might just take me a few days sometimes.

**Comment by m-cat** [comment]
> Looks like the test are failing. Also would it be a lot of effort to mock those requests again? I'd much rather have those as unit tests than integration tests if possible.

@kwypchlo It looks like they will be added in https://github.com/SkynetLabs/nodejs-skynet/pull/157!

**Review by ro-tex — APPROVED** [review]

**Review by kwypchlo — APPROVED** [review]

**Pull request merged**
