### PR TITLE
Remove_encryption_module_fix1

### PR DESCRIPTION
**Pull request by parajbs**
changelog:
- remove "src/encryption.js" and clean the code
- remove alle code with "onUploadProgress" und "onDownloadProgress"

# PULL REQUEST

## Checklist

- [ ] All git commits are signed. (REQUIRED)
- [ ] All new methods or updated methods have clear docstrings.
- [ ] Testing added or updated for new methods.
- [ ] Verified if any changes impact the WebPortal Health Checks.
- [ ] Appropriate documentation updated.
- [ ] Changelog file created.

### CODE REVIEW

**Comment by m-cat** [comment]
Looks good to me, except I think you also should remove `encryption.js`.

Just a note though: Skynet Labs is in the process of shutting down. I no longer work there and am not able to approve PRs. @kwypchlo should still have that power for the time being, but please be aware that the future of these repositories is uncertain right now.

Cheers, was great working with you. 😢

**Comment by kwypchlo** [comment]
> Looks good to me, except I think you also should remove `encryption.js`.

agreed

**Comment by parajbs** [comment]
Hello **m-cat and kwypchlo,**

Sorry, forgot to delete it.

Thanks for the info m-cat, I've already read it but didn't quite understand what's shutting down and what's staying online.
m-cat, maybe you know?

I'm sorry you don't work there anymore.
I just followed her profile on Github.
Are you still involved with the project?

Working on the code with you was a lot of fun. I learned quite a bit about Github from this, **thank you.**

**What did the CEO mean by solid product?
Does he mean Skynet or Sia-UI or the complete Project?
I've been following the project since the beginning, and I've been worried about how the project is going to fund for years.**

Important questions:
1. will everything shut down?
2. And what remains?
3. Is everything open source so that the community can continue to operate it itself?

Just because the SkynetLabs company is shutting down, the project can be continued and further developed!

**Or how do you see it?**

**Review by kwypchlo — APPROVED** [review]

**Review by MSevey — APPROVED** [review]

**Comment by m-cat** [comment]
> I'm sorry you don't work there anymore.
I just followed her profile on Github.
Are you still involved with the project?

@parajbs Yeah, it was a big shock and heartbreak to the team! I'll definitely stay casually involved in Skynet as David and the community seem keen on pushing it forwards. They are welcome to consult me as I have a lot of knowledge that may continue to be helpful. However, I need to move on to new full-time opportunities.

> Working on the code with you was a lot of fun. I learned quite a bit about Github from this, thank you.

That makes me really happy to hear. I really enjoyed working with you! 🥹

I don't have answers to the rest of your questions. I highly recommend you go on our Discord and join the discussion there!

**Comment by dghelm** [comment]
> Important questions:
> will everything shut down?
> And what remains?
> Is everything open source so that the community can continue to operate it itself?

If you haven't already, take a look at the [announcement](https://skynetlabs.com/news/skynet-labs-shutting-down-skynet-remains-online).

The work underway currently is to try and make the portal infrastructure easier for anyone to run so that community members can continue stewarding the project. Everything is open-source, and the Sia Foundation has generously stepped up to help the team find more avenues for funding some infrastructure and development, even in the absence of the Skynet Labs team.

@parajbs Thank you so much for your contributions, and I'd echo @m-cat suggestion of joining the Discord server if you haven't already. The community will need more leaders who are familiar with the codebase, and your input will be of great value.

**Comment by parajbs** [comment]
Hello **dghelm and m-cat,**

I also have several **Discord accounts, parajbs and parajbs2**, but at the moment I can only be reached via parajbs2 on Discord.
However, I usually only inform myself about renewals and problems that you are trying to eliminate.

> If you haven't already, take a look at the [announcement](https://skynetlabs.com/news/skynet-labs-shutting-down-skynet-remains-online).

Yes, I have read and worked through the post several times so that I understand everything correctly.

> The work underway currently is to try and make the portal infrastructure easier for anyone to run so that community members can continue stewarding the project.

I'll be surprised what comes out of it.

> Everything is open-source, and the Sia Foundation has generously stepped up to help the team find more avenues for funding some infrastructure and development, even in the absence of the Skynet Labs team.

Let's see if I can help you with that.
However, I don't come from the marketing area, but rather a developer.
I run a private decentralized network with about 25 nodes based on "ipfs(kubo)" for the company. However, I mainly work with the "experimental features" of "ipfs(kubo)" to provide internal and external information and apps for employees.

> @parajbs Thank you so much for your contributions, and I'd echo @m-cat suggestion of joining the Discord server if you haven't already. The community will need more leaders who are familiar with the codebase, and your input will be of great value.

I guess that shouldn't be a problem, I've just always held back because I:

1. Always have to write everything in English so that you can understand it. Since google translater often translates crap, it is more complex for me.

2. Because I've only ever observed the project in Discord before and closed-sourced ideas that I liked for myself to test things.

3. The most important reason is because it's your project and I thought it's going pretty well.
I also didn't want to cause too much stress in your project with my ideas.

4. And sometimes I'd rather do it than explain it in a way you'll understand.

**Pull request merged**
